#!/bin/bash

cd ~/.vim/bundle && git clone https://github.com/rking/ag.vim ag && vim +Helptags
cd ~/.vim && git clone https://github.com/kien/ctrlp.vim.git bundle/ctrlp.vim
cd ~/.vim/bundle && git clone https://github.com/Shougo/neocomplcache.vim.git 
cd ~/.vim/bundle && git clone git://github.com/tpope/vim-vinegar.git
cd ~/.vim/bundle && git clone https://github.com/scrooloose/syntastic.git
cd ~/.vim/bundle && git clone git://github.com/tpope/vim-fugitive.git
cd ~/.vim/bundle && git clone git://github.com/tpope/vim-surround.git
cd ~/.vim/bundle && git clone git://github.com/tpope/vim-unimpaired.git
cd ~/.vim/bundle && git clone git://github.com/vim-scripts/vimwiki.git
