#!/bin/sh

usage() {
    cat <<EOF
Usage: $0 DELTA

DELTA    The value to add to current brightness
EOF
}

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

brightness=$(cat /sys/class/backlight/gmux_backlight/actual_brightness)

brightness=$(( $brightness + $1 ))

echo $brightness | sudo tee /sys/class/backlight/gmux_backlight/brightness
