#!/bin/sh

usage() {
    cat <<EOF
Usage: $0 DELTA

DELTA    The value to add to current brightness
EOF
}

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

brightness=$(printf "%.0f\n" $(xbacklight))

brightness=$(( $brightness + $1 ))

xbacklight -set $brightness
